
/**
 * Search and social metadata helpers.
 *
 * ## The bug this file exists to prevent
 *
 * Every project, episode, news post and team member on this site shipped with
 * **no share image at all**: paste the link into Discord and you get a bare URL.
 * The site has a perfectly good default at `app/opengraph-image`, and the
 * listing pages were using it — the detail pages were not.
 *
 * The reason is a merge rule that is easy to get backwards. Next merges metadata
 * shallowly, and `openGraph` is *replaced* by a child route rather than merged
 * into. So the moment a page declares an `openGraph` block — to set a type, a
 * URL, an article timestamp — it drops the parent's images too, including the
 * ones the file convention contributed. Writing
 *
 *     openGraph: { images: cover ? [{ url: cover }] : undefined }
 *
 * therefore fails twice over: the `undefined` claims the slot, and even leaving
 * the key out entirely would not bring the fallback back.
 *
 * The fix has to be explicit. `ogImages()` falls back to the site image by
 * itself, so a page can only end up with no share image by not calling it.
 */

/**
 * The site-wide share image, generated by `app/opengraph-image`.
 *
 * Spelled out as a URL rather than relied on as a convention, because the
 * convention does not survive a page declaring its own `openGraph` block.
 */
export function defaultOgImage(): string {
  /*
    Relative on purpose.

    Next resolves a relative `openGraph.images` entry against `metadataBase`,
    which the root layout now derives from the request — so this needs no origin
    of its own, and cannot go stale against one. An absolute URL built here from
    `NEXT_PUBLIC_SITE_URL` was exactly the bug: unset the variable and every
    share card pointed at `localhost:3000/opengraph-image`.
  */
  return '/opengraph-image';
}

/**
 * Open Graph image entry, with the site image as the floor.
 *
 * Spread it — `...ogImages(url)` — into an `openGraph` block. There is
 * deliberately no way for this to return nothing: a page with no share image is
 * a link that renders as a bare URL everywhere it is posted, and for a fansub
 * that posts every release into Discord, that is the cost that actually shows.
 */
export function ogImages(
  url: string | null | undefined,
  alt?: string,
): { images: Array<{ url: string; width: number; height: number; alt?: string }> } {
  // 1200×630 is what every major platform crops to; stating it lets them lay
  // out the card before the image has finished downloading.
  return {
    images: [{ url: url || defaultOgImage(), width: 1200, height: 630, ...(alt ? { alt } : {}) }],
  };
}

/** The Twitter card variant, which takes bare URLs rather than objects. */
export function twitterImages(url: string | null | undefined): { images: string[] } {
  return { images: [url || defaultOgImage()] };
}

export interface BreadcrumbEntry {
  name: string;
  /**
   * Absolute path of the crumb. Omit it for the final entry — schema.org treats
   * the last item as "the page you are on", and giving it a URL that is not this
   * page's own is worse than giving it none.
   */
  path?: string;
}

/**
 * `BreadcrumbList` structured data.
 *
 * Built from the same array the visible trail renders from, which is the only
 * way to guarantee the two agree. Breadcrumb markup that disagrees with the page
 * is worse than none: search engines treat the mismatch as a reason to distrust
 * the rest of the page's structured data.
 */
export function breadcrumbJsonLd(entries: BreadcrumbEntry[], base: string): string {
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: entries.map((entry, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: entry.name,
      ...(entry.path ? { item: `${base}${entry.path.startsWith('/') ? entry.path : `/${entry.path}`}` } : {}),
    })),
  });
}

/**
 * Site-level identity, emitted once on the home page.
 *
 * Two things in one graph:
 *
 * - **Organization** is what a search engine attaches a logo and social profiles
 *   to. Without it a fansub is an anonymous domain; with it the name and mark
 *   can appear beside the results.
 * - **WebSite** with a `SearchAction` is what offers the search box directly in
 *   the result listing. The site already has `/kereses?q=` — this is only
 *   telling anyone about it.
 */
export function siteJsonLd(siteName: string, description: string, url: string): string {

  return JSON.stringify({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${url}/#organization`,
        name: siteName,
        url,
        description,
        logo: `${url}/opengraph-image`,
      },
      {
        '@type': 'WebSite',
        '@id': `${url}/#website`,
        name: siteName,
        url,
        description,
        inLanguage: 'hu-HU',
        publisher: { '@id': `${url}/#organization` },
        potentialAction: {
          '@type': 'SearchAction',
          target: {
            '@type': 'EntryPoint',
            urlTemplate: `${url}/kereses?q={search_term_string}`,
          },
          'query-input': 'required name=search_term_string',
        },
      },
    ],
  });
}
